version: "3.9"

services:
  static_analyze:
    build:
      context: .
      dockerfile: ./docker/static.Dockerfile
    ports:
      - "8090:8090"
    env_file:
      - ".env"
    container_name: static_analyze_container

networks:
   default:
     name: "connect-service"
     external: true